name: FakeStore Tests
on: [pull_request]
jobs:
    cypress-run:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: cypress-io/github-action@v4
              with:
                  start: npm run preview
                  browser: chrome
                  #   headless: true
